/**
 * Script to generate base64-encoded font files for Cloudflare Workers
 *
 * Run this script from the worker directory:
 *   node scripts/generate-fonts.js
 *
 * This will read the TTF fonts from the backend/fonts directory
 * and create a TypeScript file with the fonts embedded as base64.
 */

const fs = require('fs');
const path = require('path');

const fontsDir = path.join(__dirname, '../../backend/fonts');
const outputFile = path.join(__dirname, '../src/fonts/notoSans.ts');

// Read font files
const regularFontPath = path.join(fontsDir, 'NotoSans-Regular.ttf');
const boldFontPath = path.join(fontsDir, 'NotoSans-Bold.ttf');

if (!fs.existsSync(regularFontPath)) {
  console.error(`Font file not found: ${regularFontPath}`);
  process.exit(1);
}

if (!fs.existsSync(boldFontPath)) {
  console.error(`Font file not found: ${boldFontPath}`);
  process.exit(1);
}

const regularFont = fs.readFileSync(regularFontPath);
const boldFont = fs.readFileSync(boldFontPath);

const regularBase64 = regularFont.toString('base64');
const boldBase64 = boldFont.toString('base64');

// Generate TypeScript file
const tsContent = `/**
 * Embedded Noto Sans fonts for PDF generation in Cloudflare Workers
 *
 * Generated by: node scripts/generate-fonts.js
 * Generated at: ${new Date().toISOString()}
 *
 * These fonts are embedded as base64 strings and converted to ArrayBuffer
 * at runtime for use with PDFKit.
 */

// Base64-encoded NotoSans-Regular.ttf
const NOTO_SANS_REGULAR_BASE64 = '${regularBase64}';

// Base64-encoded NotoSans-Bold.ttf
const NOTO_SANS_BOLD_BASE64 = '${boldBase64}';

/**
 * Decode base64 string to ArrayBuffer
 */
function base64ToArrayBuffer(base64: string): ArrayBuffer {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes.buffer;
}

/**
 * Get NotoSans-Regular font as ArrayBuffer
 */
export function getNotoSansRegular(): ArrayBuffer {
  return base64ToArrayBuffer(NOTO_SANS_REGULAR_BASE64);
}

/**
 * Get NotoSans-Bold font as ArrayBuffer
 */
export function getNotoSansBold(): ArrayBuffer {
  return base64ToArrayBuffer(NOTO_SANS_BOLD_BASE64);
}

/**
 * Get both fonts as a map for PDFKit registration
 */
export function getNotoSansFonts(): { regular: ArrayBuffer; bold: ArrayBuffer } {
  return {
    regular: getNotoSansRegular(),
    bold: getNotoSansBold(),
  };
}
`;

// Ensure output directory exists
const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write the file
fs.writeFileSync(outputFile, tsContent, 'utf8');

console.log(`Font embeddings generated successfully!`);
console.log(`Output: ${outputFile}`);
console.log(`Regular font size: ${(regularBase64.length / 1024).toFixed(2)} KB (base64)`);
console.log(`Bold font size: ${(boldBase64.length / 1024).toFixed(2)} KB (base64)`);
